Add missing feature in next-swc (#40550)
`shake_exports` relies on `ecma_transforms_optimization`, otherwise this will be thrown if running tests:

```
error[E0433]: failed to resolve: could not find `optimization` in `transforms`
 --> crates/core/src/shake_exports.rs:7:23
  |
7 |     ecma::transforms::optimization::simplify::dce::{dce, Config as DCEConfig},
  |                       ^^^^^^^^^^^^ could not find `optimization` in `transforms`
```

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)